var app = new Vue({
    el:"#app",
    data(){
        return{
            paymentRecord:[
                { 
                    year:"2022",
                    date:"01/31",
                    content:"網路轉帳繳款-聯邦",
                    details:[
                        {name:"繳款日",date:"01/31"},
                        {name:"入帳日",date:"01/31"},
                    ],
                    amount:"4,080",
                    flag:false
                },
                { 
                    year:"2022",
                    date:"02/28",
                    content:"網路轉帳繳款-聯邦",
                    details:[
                        {name:"繳款日",date:"02/28"},
                        {name:"入帳日",date:"02/28"},
                    ],
                    amount:"1,200",
                    flag:false
                },
                { 
                    year:"2022",
                    date:"03/31",
                    content:"網路轉帳繳款-聯邦",
                    details:[
                        {name:"繳款日",date:"03/31"},
                        {name:"入帳日",date:"03/31"},
                    ],
                    amount:"1,900",
                    flag:false
                },
                { 
                    year:"2022",
                    date:"04/30",
                    content:"網路轉帳繳款-聯邦",
                    details:[
                        {name:"繳款日",date:"04/30"},
                        {name:"入帳日",date:"04/30"},
                    ],
                    amount:"2,500",
                    flag:false
                },
            ]
        }
    },
    methods:{
        stretch:function(i){
            this.paymentRecord[i].flag = !this.paymentRecord[i].flag
        }
    },
    computed:{

    },
    mounted(){
        this.stretch()
    }
})